[package]
name = "clap-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }

[dev-dependencies]
clap = { version = "4.4", features = ["derive", "env"] }
url = "2.5"
